# 使用扩展字段定义公共模板
x-nginx-common: &nginx-common
  image: nginx:1.27-alpine
  env_file: [.env]
  environment: &nginx-common-env
    UPLOAD_DIR: ${UPLOAD_DIR:-uploads}
    API_PREFIX: ${API_PREFIX:-/api}
    API_UPSTREAM_HOST: ${API_UPSTREAM_HOST:-app}
    API_UPSTREAM_PORT: ${API_UPSTREAM_PORT:-8090}
    NGINX_ENVSUBST_FILTERED_VAR_NAMES: UPLOAD_DIR API_PREFIX API_UPSTREAM_HOST API_UPSTREAM_PORT API_PORT
  ports:
    - '${NGINX_PORT:-80}:80'
  # 统一使用外部脚本作为入口
  entrypoint: ['/entrypoint.sh']
  volumes:
    # 挂载脚本
    - ./nginx/entrypoint.sh:/entrypoint.sh:ro
    # 挂载配置模板
    - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro

services:
  app:
    build: .
    profiles: ['prod']
    env_file: [.env]
    environment:
      - API_UPSTREAM_PORT=${API_UPSTREAM_PORT:-8090}
    ports:
      - '${API_PORT}:${API_UPSTREAM_PORT}'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - uploads_data:/app/${UPLOAD_DIR:-uploads}

  nginx-dev:
    <<: *nginx-common
    profiles: ['dev']
    environment:
      <<: *nginx-common-env
      NODE_ENV: development
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./uploads:/var/www/${UPLOAD_DIR:-uploads}:ro

  nginx:
    <<: *nginx-common
    profiles: ['prod']
    environment:
      <<: *nginx-common-env
      NODE_ENV: production
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - uploads_data:/var/www/${UPLOAD_DIR:-uploads}:ro

  db:
    image: postgres:16-alpine
    profiles: ['prod', 'dev']
    env_file: [.env]
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_OWNER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_OWNER_PASSWORD}
      POSTGRES_TIMEZONE: Asia/Shanghai
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  uploads_data:
